### ISSUE TITLE
comicflow server unreachable

### ISSUE THREAD

**Issue by prostatadimele** [swisspol/ComicFlow#108]
Hi, here's Domenico.
I bought complete version of comicflow several months ago. I used a lot of times the feature of comicflow web server, but it seems it doesn't work anymore. I tried different browsers, different computers, different wi-fi services, but nothing.

Thanks a lot for the support.

**Comment by swisspol** [comment]
Hi,

ComicFlow is the exact same app version since probably a year, so nothing at all has changed there. 

Did you try using WebDAV server with an app like [CyberDuck](https://cyberduck.io/?l=en) instead of the Website Server with your web browser? See the app's description at https://itunes.apple.com/us/app/comicflow/id409290355?mt=8 for more information.
