### ISSUE TITLE
Use 'fit-to-width' mode when in landscape

### ISSUE THREAD

**Issue by mad0908** [swisspol/ComicFlow#14]
The app is difficult to use in landscape mode. When opening a new page, it should automatically adjust the zoom to align the left, right and top of the page to the left, right and top of the display (instead of aligning the top and bottom of the page to the top and bottom of the display).

**Comment by EvilSquirrel** [comment]
Many apologies for the long delay, but I finally got around to setting up Git (looks like I'll have to learn and use it at work soon enough anyway) and reproducing my old changes on top of the current codebase. In the process I cleaned it up and improved it a bit. I haven't tested it on a device yet - I'm pretty sure that would require messing with the project because of the 3rd party libraries; but I have no reason to suspect that the behaviour would be different. I will be making a pull request shortly (well two actually, there's a few small changes in Cooliris-toolkit) but please bear in mind that this is my first crack at using Git, so if I mess anything up let me know :)

**Comment by swisspol** [comment]
Check out http://gitup.co, it sure will help with the Git side of things :)

**Comment by EvilSquirrel** [comment]
I've already read a number of articles and how-to's and I think I've got the basics ok... That site looks nicely done so I'll take a look.

**Comment by swisspol** [comment]
As a Git newcomer, I'd say you wanna use GitUp if only for one crucial feature: undo / redo. No other Git tool offers undo / redo although it can save your day.

**Comment by EvilSquirrel** [comment]
By the way, there are a few other changes I made that could be considered for inclusion (as-is or with small changes) but some of the stuff I experimented with did require changing the database format, so those might understandably be less attractive. Aside for a few small bug fixes (which I can contribute after checking if they still exist), the main things I worked on are a "Delete all read" command, comic locking, an info popup window, and filename-based metadata.

Maybe I just overlooked it, but I haven't seen any tools in Github for exchanging message outside of these issue reports, so if you are interested let me know how you prefer to communicate.

**Comment by swisspol** [comment]
Changing the database format is not an option unfortunately, it's way too risky.

Communication on GitHub happens through issues indeed. It works fine :)

**Comment by EvilSquirrel** [comment]
Allrighty then :)
"Delete all read" is the safe one, I don't recall it needing anything special. The locking was done using a new database field, but it could perhaps be redone using the status field only; however that might require additional changes to the code that uses the status field for, well, status... The info popup is just GUI code, but it was integrated with the metadata changes, and it's not nearly as useful without them.
