### ISSUE TITLE
Wifi crashing when importing CBR/CBZ files

### ISSUE THREAD

**Issue by gittarman** [swisspol/ComicFlow#80]
I'm noticing that every time I connect to the web server to import my files to my ComicFlow on my iPad 3 (running iOS 8.1.2) my Wifi goes down and doesn't come back for a while.  So I open the app again to import my files and the wifi goes down again.  It doesn't happen with any other app and I can surf normally and receive emails whenever the wifi does come back up.

**Comment by swisspol** [comment]
What do you exactly mean by "wifi goes down"? You entire Wifi network? WiFi on your computer? On your iPad?

No matter what, I can assure you that although this appears related to ComicFlow, this is in no way *caused* by it. All ComicFlow does is run a passive webserver on port 80: it's not going to mess up with your WiFi network. It's just not possible. You're not trying to "connect" to your iPad with the other apps you mention like you do with ComicFlow, so that would expose the network problem you're having.

Maybe your WiFi router is not configured correctly and it's messing up with your computer is trying to talk directly to your iPad over WiFi vs each device talking only to the Internet. Or your WiFi router is giving to the iPad an already used IP address instead of a unique one, or the same is happening with your computer... It's a WiFi network problem, not a ComicFlow problem I'm afraid.

**Comment by gittarman** [comment]
Ok, good, thank you for your help.  I can work backwards with this.  I appreciate your input and SUPER fast response.  

.........any chance you guys can run for Congress? lol

**Comment by swisspol** [comment]
I wish ;) Good luck tracking this down, I know these WiFi router issues can be a pain! Also in case you're using a Mac with Yosemite WiFi is very unstable on this version of OS X (it randomly disconnects now and then), so that could be a factor too.
