### ISSUE TITLE
Can't upload files on ComicFlow

### ISSUE THREAD

**Issue by randfaulknersw** [swisspol/ComicFlow#88]
I recently updated to El Capitan on my iMac, and have updated my iPad to iOS 9.1. Since the updates, I can still get to the ComicFlow server via a web browser on the iMac where it says, "You are successfully connected to the ComicFlow app on your iPad." 

However, once I get to that point, any new file that I try to upload to the iPad's library fails and returns an error message that says the upload failed. The file formats are correct and match the same formats I've always used in the past (e.g., .cbr). The same issue exists across more than one browser (I've used Safari and Chrome with the same results.)

Is there a setting I should be looking at? Basically, I can connect to the ComicFlow server but all uploads fail. Help!!!

**Comment by randfaulknersw** [comment]
Here is an example of the error message I receive:

error: Failed uploading "Chewbacca 01 (of 05) (2015) (Digital) (Kileko-Empire).cbr" to "/"

**Comment by randfaulknersw** [comment]
Is there some other place I should be requesting help???

**Comment by randfaulknersw** [comment]
I just finished a chat with Apple support, they say:

“As a boost in security El Capitan implements a requirement for web servers to have https implementation to ensure that your data cannot be compromised during a transfer. This feature is hardwired in the OS X El Capitan and iOS 9 and would likely require an update of the App to implement the secured form of connection.”

Is there any update in the works?

**Comment by swisspol** [comment]
ComicFlow is not affected by this security change in iOS 9.1: it still works exactly the same and nobody has reported any issues.

What's more likely to happen is that the app you use to upload comics to ComicFlow from your Mac needs updating for El Capitan. The OS X version might block apps trying to communicate over HTTP instead of HTTPS, unless they have an exception. ComicFlow is HTTP only so that would be needed.

In the meantime, you can use a different app like a Transmit, or a different web browser.
